### ISSUE TITLE
Pass note when triggering the action

### ISSUE THREAD

**Issue by v-dimitroff** [SpeedCurve-Metrics/speedcurve-test-action#63]
I couldn't find a way to pass the name of the PR triggering the action as a note or something so that I can track back from the dashboard which run matches which PR.

Are you planning to add this?

**Comment by wildlyinaccurate** [comment]
Hey, thanks for raising this! At the moment the deploy note is hard-coded, but it would make sense for it to be a parameter to the action.

**Comment by v-dimitroff** [comment]
Sure, will love to see this in production :)

**Comment by v-dimitroff** [comment]
Hi there @wildlyinaccurate, I was wondering if you are considering of merging this PR. We find your product very useful but this lack of option to name our runs is making it really hard to distinguish when something has got worng.

**Comment by josephwynn-sc** [comment]
Sorry @v-dimitroff, I've been a bit busy! I'll tag & release a new version later today :)

**Comment by v-dimitroff** [comment]
Hey @wildlyinaccurate , thanks for the lightning response! No worries, I completely understand business! And thank you a bunch for merging this PR. We immediately get use of it and it all looks even more beautiful now!
