### ISSUE TITLE
Note field logic isn't working

### ISSUE THREAD

**Issue by CodingSamurai** [SpeedCurve-Metrics/speedcurve-test-action#70]
When I attempted to use the custom note field to pass along information about the merge I'm getting an error:

`Unexpected input(s) 'note', valid inputs are ['api_key', 'site_id', 'url_id', 'replace_origin']`

My .yml file includes the following information:

`- name: RUN SPEEDCURVE TESTS
     uses: SpeedCurve-Metrics/speedcurve-test-action@v1.2.1
        with:
          api_key: "<API KEY>"
          site_id: <SITE ID>
          note: "Merge ${{ github.ref }} by ${{github.actor}}"
`

**Comment by josephwynn-sc** [comment]
The `note` parameter was added in v1.2.2. Update the version in your YAML and it should work.

**Comment by josephwynn-sc** [comment]
I will update the README to use v1.2.2 in the examples :)
