### ISSUE TITLE
V1.2.2 not available in marketplace

### ISSUE THREAD

**Issue by CFsylvester** [SpeedCurve-Metrics/speedcurve-test-action#74]
I would like to use the "note" filed in my GitHub actions. Due to this being available in your documentation as a recent release, I was under the impression v1.2.2 is available. However, when I check the marketplace (https://github.com/marketplace/actions/run-speedcurve-tests) the newest release is v1.2.1. When will v1.2.2 be available for use? Or is there something else I can do to implement this "note" field in the yml?

**Comment by josephwynn-sc** [comment]
Thank you for reporting this! It turns out there was a new developer agreement that we had to accept before GitHub would publish the latest version. It should be available in the marketplace now.
